### ISSUE TITLE
Replace pgbackups since it's been deprecated

### ISSUE THREAD

**Issue by thinkmorebetter** [rainforestapp/fourchette#56]
Looks like trying to add `pgbackups` now results in `No such add-on plan` preventing db copy. I'm not sure if there's another way to do it, the Platform API doesn't seem to have anything.

**Comment by scruti** [comment]
Yesterday we also started experiencing issues with pgbackups:
> 2015-03-12T12:04:33.551195+00:00 app[web.1]: I, [2015-03-12T12:04:33.551085 #45]  INFO -- : Adding pgbackups:plus to verema-pr-940
> 2015-03-12T12:04:33.660127+00:00 app[web.1]: E, [2015-03-12T12:04:33.660015 #45] ERROR -- : Failed to copy addon pgbackups:plus

**Comment by jipiboily** [comment]
Oh, this is so sad! If someone has time to work on this, that would be ace! I don't need this yet myself, but that would make sense as this is broken for anyone using a new-ish app.

**Comment by wless1** [comment]
I am working on a fix, and I've love some feedback. It's #57

**Comment by skatkov** [comment]
So, it appears I ran into similar issue. I have other addons from production environment, which it can't add... but it crashes only on pgbackups 

```ruby
2015-05-07T09:21:31.323784+00:00 app[web.1]: I, [2015-05-07T09:21:31.323670 #11]  INFO -- : Adding pgbackups to inboundsms
2015-05-07T09:21:31.413107+00:00 app[web.1]: E, [2015-05-07T09:21:31.413026 #11] ERROR -- : Fourchette::PullRequest crashed!
2015-05-07T09:21:31.413111+00:00 app[web.1]: Excon::Errors::UnprocessableEntity: Expected([200, 201, 202, 206, 304]) <=> Actual(422 Unprocessable Entity)
2015-05-07T09:21:31.413112+00:00 app[web.1]:
2015-05-07T09:21:31.413114+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/excon-0.39.5/lib/excon/middlewares/expects.rb:6:in `response_call'
2015-05-07T09:21:31.413115+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/excon-0.39.5/lib/excon/middlewares/response_parser.rb:8:in `response_call'
2015-05-07T09:21:31.413117+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/excon-0.39.5/lib/excon/connection.rb:363:in `response'
2015-05-07T09:21:31.413119+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/excon-0.39.5/lib/excon/connection.rb:233:in `request'
2015-05-07T09:21:31.413121+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/heroics-0.0.12/lib/heroics/link.rb:60:in `run'
2015-05-07T09:21:31.413122+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/heroics-0.0.12/lib/heroics/resource.rb:27:in `method_missing'
2015-05-07T09:21:31.413123+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/platform-api-0.2.0/lib/platform-api/client.rb:415:in `create'
2015-05-07T09:21:31.413125+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/fourchette-0.1.1/lib/fourchette/pgbackups.rb:24:in `ensure_pgbackups_is_present'
2015-05-07T09:21:31.413127+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/fourchette-0.1.1/lib/fourchette/pgbackups.rb:10:in `copy'
2015-05-07T09:21:31.413129+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/fourchette-0.1.1/lib/fourchette/heroku.rb:70:in `copy_pg'
2015-05-07T09:21:31.413130+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/fourchette-0.1.1/lib/fourchette/heroku.rb:12:in `fork'
2015-05-07T09:21:31.413131+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/fourchette-0.1.1/lib/fourchette/fork.rb:61:in `create_unless_exists'
2015-05-07T09:21:31.413133+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/fourchette-0.1.1/lib/fourchette/fork.rb:38:in `create'
2015-05-07T09:21:31.413134+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/fourchette-0.1.1/lib/fourchette/pull_request.rb:20:in `perform'
2015-05-07T09:21:31.413135+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'
2015-05-07T09:21:31.413136+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
2015-05-07T09:21:31.413138+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:67:in `dispatch'
2015-05-07T09:21:31.413139+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `block in handle_message'
2015-05-07T09:21:31.413140+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `block in task'
2015-05-07T09:21:31.413142+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `block in initialize'
2015-05-07T09:21:31.413143+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `block in create'
2015-05-07T09:21:31.414163+00:00 app[web.1]: D, [2015-05-07T09:21:31.414075 #11] DEBUG -- : Celluloid::PoolManager: async call `perform` aborted!
2015-05-07T09:21:31.414166+00:00 app[web.1]: Excon::Errors::UnprocessableEntity: Expected([200, 201, 202, 206, 304]) <=> Actual(422 Unprocessable Entity)
2015-05-07T09:21:31.414168+00:00 app[web.1]:
2015-05-07T09:21:31.414169+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/excon-0.39.5/lib/excon/middlewares/expects.rb:6:in `response_call'
2015-05-07T09:21:31.414171+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/excon-0.39.5/lib/excon/middlewares/response_parser.rb:8:in `response_call'
2015-05-07T09:21:31.414172+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/excon-0.39.5/lib/excon/connection.rb:363:in `response'
2015-05-07T09:21:31.414173+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/excon-0.39.5/lib/excon/connection.rb:233:in `request'
2015-05-07T09:21:31.414175+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/heroics-0.0.12/lib/heroics/link.rb:60:in `run'
2015-05-07T09:21:31.414176+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/heroics-0.0.12/lib/heroics/resource.rb:27:in `method_missing'
2015-05-07T09:21:31.414177+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/platform-api-0.2.0/lib/platform-api/client.rb:415:in `create'
2015-05-07T09:21:31.414179+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/fourchette-0.1.1/lib/fourchette/pgbackups.rb:24:in `ensure_pgbackups_is_present'
2015-05-07T09:21:31.414180+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/fourchette-0.1.1/lib/fourchette/pgbackups.rb:10:in `copy'
2015-05-07T09:21:31.414182+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/fourchette-0.1.1/lib/fourchette/heroku.rb:70:in `copy_pg'
2015-05-07T09:21:31.414183+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/fourchette-0.1.1/lib/fourchette/heroku.rb:12:in `fork'
2015-05-07T09:21:31.414184+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/fourchette-0.1.1/lib/fourchette/fork.rb:61:in `create_unless_exists'
2015-05-07T09:21:31.414186+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/fourchette-0.1.1/lib/fourchette/fork.rb:38:in `create'
2015-05-07T09:21:31.414187+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/fourchette-0.1.1/lib/fourchette/pull_request.rb:20:in `perform'
2015-05-07T09:21:31.414189+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'
2015-05-07T09:21:31.414190+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
2015-05-07T09:21:31.414192+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:67:in `dispatch'
2015-05-07T09:21:31.414193+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `block in handle_message'
2015-05-07T09:21:31.414194+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `block in task'
2015-05-07T09:21:31.414195+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `block in initialize'
2015-05-07T09:21:31.414214+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `block in create'
2015-05-07T09:21:31.414216+00:00 app[web.1]: 	(celluloid):0:in `remote procedure call'
2015-05-07T09:21:31.414218+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:92:in `value'
2015-05-07T09:21:31.414219+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
2015-05-07T09:21:31.414220+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/proxies/actor_proxy.rb:20:in `_send_'
2015-05-07T09:21:31.414221+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/pool_manager.rb:41:in `_send_'
2015-05-07T09:21:31.414222+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/pool_manager.rb:123:in `method_missing'
2015-05-07T09:21:31.414224+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'
2015-05-07T09:21:31.414225+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
2015-05-07T09:21:31.414226+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:122:in `dispatch'
2015-05-07T09:21:31.414238+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `block in handle_message'
2015-05-07T09:21:31.414239+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `block in task'
2015-05-07T09:21:31.414240+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `block in initialize'
2015-05-07T09:21:31.414242+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `block in create'
```

**Comment by jipiboily** [comment]
Anyone tried @wless1's PR or has other fixes? Thanks!

**Comment by jipiboily** [comment]
FYI, we just decided to deprecate Fourchette. You can (and probably should) use the Heroku review apps instead which was inspired by Fourchette. 

https://devcenter.heroku.com/articles/github-integration-review-apps

Thanks!
